# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageDebuggerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageDebuggerExample
  pod 'OpenCV'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

end
